### ISSUE TITLE
Integration of the Central Authentication Service (CAS)

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#155]

**Comment by jtranier** [comment]
elaastic allows to configure one or several CAS authentication servers in addition of the internal authentication mechanism.

*CAS configuration*
The CAS config is defined into the `application.properties` file.
Each CAS server must be identified by a unique `casKey`. The property `cas.keyList` is a comma-separated value defining the list of key of each CAS server.

Each CAS server will have the following config : 
- `cas.<casKey>.server.url` : the URL of the CAS server
- `cas.<casKey>.label` and `cas.<casKey>.logo` are used on the elaastic login page to expose the CAS server to users.

*Cinematic*
A specific _entrypoint_ is configured for URL of the form `/cas/<casKey>/<path>` ; if there is no user authenticated the application will emit a redirect on the CAS server login page ; otherwise it will emit a redirect to `/<path>`.

When a CAS server authenticates a user it will redirect on `<elaastic>/cas/login/{casKey}?ticket=xxx`. elaastic will validate the ticket and authenticate the elaastic user account corresponding for the provided login and casKey. If the user account does not exist it will be created on the fly.
The table `cas_user` store the mapping between `(cas_login, cas_key) => elaastic_login`.
